alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias cd..='cd ..'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='lsd -F --group-directories-first'
alias la='lsd -A --group-directories-first'
alias ll='lsd -alF --group-directories-first'
alias ls='lsd --color=auto --group-directories-first'
alias md='mkdir'
alias open='explorer.exe'
alias py='python3'
alias update='sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y'
alias cls='clear -x'
alias v='nvim'
alias pip='py -m pip'
alias kogex='ssh -X -t koge@143.93.91.124 "cd /media/BioNAS/KOGE_WS_23_24 ; bash --login"'
alias bio='ssh -t studaghal@143.93.91.50'
alias koge='ssh -t koge@143.93.91.124 "cd /media/BioNAS/KOGE_WS_23_24 ; bash --login"'
alias less='less -S'
alias crean='sed -i "s/\r//g"'
alias ppush='git push origin franz-playground && git push private franz-playground:master'
alias bppush='git push origin && git push private'
alias e='open .'
alias t='wt.exe'
