alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias cd..='cd ..'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='lsd -F --group-directories-first'
alias la='lsd -A --group-directories-first'
alias ll='lsd -alF --group-directories-first'
alias ls='lsd --color=auto --group-directories-first'
alias md='mkdir'
alias open='explorer.exe'
alias py='python3'
alias update='sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y'
alias cls='clear -x'
alias v='nvim'
alias pip='py -m pip'